#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016-2020 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under
#   the terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.

---

- name: Remove OpenBACH repository
  apt_repository: repo={{ item }} state=absent update_cache=yes
  with_items: "{{ openbach_repository }}"
  become: yes
  environment: "{{ openbach_proxy_env }}"

- name: Stop Agent Services
  systemd: name={{ item }} state=stopped enabled=no daemon_reload=yes
  with_items:
    - openbach_agent
    - rstats
  become: yes

- name: Remove Agent Services Files
  file: path=/etc/systemd/system/{{ item }}.service state=absent
  with_items:
    - openbach_agent
    - rstats
  become: yes

- name: Remove pip Mirror
  file: path=/opt/openbach/pip_mirror state=absent
  become: yes

- name: Restore ntp Backup
  shell: ls -t1 ntp.conf.* | tail -1 | xargs -I XXX mv XXX ntp.conf chdir=/etc/
  ignore_errors: yes
  become: yes

- name: Remove Log Folder
  file: path=/var/log/openbach state=absent
  become: yes
  when: openbach_clear_databases | default(False)

- name: Remove logrotate Config File
  file: path=/etc/logrotate.d/openbach_logrotate.conf state=absent
  become: yes

- name: Remove Rsyslog Config Files
  file: path=/etc/rsyslog.d/{{ item }}.conf state=absent
  with_items:
    - rstats
    - rstats_local
    - openbach_agent
    - openbach_agent_local
  become: yes

- name: Remove Stats Folder
  file: path=/var/openbach_stats state=absent
  become: yes
  when: openbach_clear_databases | default(False)

- name: Remove Openbach API Modules
  pip: executable=pip3 name=openbach_api state=absent
  become: yes

- name: Remove Agent Repository
  file: path=/opt/openbach/agent state=absent
  become: yes

- name: Uninstall collect-agent package
  apt: name=collect-agent state=absent
  become: yes

- name: Remove SUDO Rights for openbach User
  file: path=/etc/sudoers.d/passwordless_openbach state=absent
  become: yes
