#!/usr/bin/env python3

# OpenBACH is a generic testbed able to control/configure multiple
# network/physical entities (under test) and collect data from them. It is
# composed of an Auditorium (HMIs), a Controller, a Collector and multiple
# Agents (one for each network entity that wants to be tested).
#
#
# Copyright © 2016-2023 CNES
#
#
# This file is part of the OpenBACH testbed.
#
#
# OpenBACH is a free software : you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.


"""Provide comparison of data generated by OpenBACH jobs"""


__author__ = 'Viveris Technologies'
__credits__ = '''Contributors:
 * Francklin SIMO <francklin.simo@toulouse.viveris.com>
'''

import syslog
import os.path
import argparse
import tempfile
import itertools

import matplotlib.pyplot as plt

import collect_agent
from data_access.post_processing import Statistics, save


def main(job_instance_ids, statistics_names, stats_with_suffixes, ylabels, titles, xlabel_job_instance_names, pickle):
    file_ext = 'pickle' if pickle else 'png'
    xlabel_instance_names = iter(xlabel_job_instance_names)

    statistics = Statistics.from_default_collector()
    with tempfile.TemporaryDirectory(prefix='openbach-comparison-') as root:
        for fields, ylabel, title in itertools.zip_longest(statistics_names, ylabels, titles):
            figure, axis = plt.subplots()
            data = statistics.fetch_all(
                    job_instances=job_instance_ids,
                    suffix = None if stats_with_suffixes else '',
                    fields=fields, columns=xlabel_instance_names)
            data.plot_comparison(axis, ylabel, False)
            if title is not None:
                axis.set_title(title)
            if statistics_names is None:
                filename = 'comparison.{}'.format(file_ext)
            else:
                filename = 'comparison_{}.{}'.format('_'.join(fields), file_ext)
            filepath = os.path.join(root, filename)
            save(figure, filepath, pickle)
            collect_agent.store_files(collect_agent.now(), figure=filepath)


if __name__ == '__main__':
    with collect_agent.use_configuration('/opt/openbach/agent/jobs/comparison/comparison_rstats_filter.conf'):
        parser = argparse.ArgumentParser(description=__doc__)
    
        parser.add_argument(
                'jobs', type=int, nargs='+', metavar='job',
                help='job instances to plot data from')
        parser.add_argument(
                '-s', '--stat', '--statistic', dest='statistics',
                metavar='STATISTIC', nargs='+', action='append',
                help='statistics names to plot')
        parser.add_argument(
                '-w', '--no-suffix', action='store_true',
                help='do not plot statistics with suffixes')
        parser.add_argument(
                '-y', '--ylabel', dest='ylabels',
                metavar='YLABEL', action='append', default=[],
                help='the label of y-axis')
        parser.add_argument(
                '-t', '--title', dest='titles',
                metavar='TITLE', action='append', default=[],
                help='the title of figure')
        parser.add_argument(
                '-p', '--pickle', action='store_true',
                help='allows to export figures as pickle '
                '(by default figures are exported as image)')
        parser.add_argument(
                '-l', '--xlabel_job_instance_names', action='append', default=[],
                help='x-axis names to display concerning the tests/job instances that are compared')
    
        args = parser.parse_args()
        stats = args.statistics or [None]
        stats_with_suffixes = not args.no_suffix
        main(args.jobs, stats, stats_with_suffixes, args.ylabels, args.titles, args.xlabel_job_instance_names, args.pickle)
