export const SET_TITLE = "App/SET_TITLE";
export const SET_SNACKMESSAGE = "App/SET_SNACKMESSAGE";

export const ADD_AGENT_PENDING = "App/ADD_AGENT_PENDING";
export const ADD_AGENT_SUCCESS = "App/ADD_AGENT_SUCCESS";
export const ADD_AGENT_ERROR = "App/ADD_AGENT_ERROR";

export const REMOVE_AGENT_PENDING = "App/REMOVE_AGENT_PENDING";
export const REMOVE_AGENT_SUCCESS = "App/REMOVE_AGENT_SUCCESS";
export const REMOVE_AGENT_ERROR = "App/REMOVE_AGENT_ERROR";

export const RESERVE_AGENT_PENDING = "App/RESERVE_AGENT_PENDING";
export const RESERVE_AGENT_SUCCESS = "App/RESERVE_AGENT_SUCCESS";
export const RESERVE_AGENT_ERROR = "App/RESERVE_AGENT_ERROR";

export const GET_AGENTS_PENDING = "App/GET_AGENTS_PENDING";
export const GET_AGENTS_SUCCESS = "App/GET_AGENTS_SUCCESS";
export const GET_AGENTS_ERROR = "App/GET_AGENTS_ERROR";

export const GET_AGENTS_VERBOSE_PENDING = "App/GET_AGENTS_VERBOSE_PENDING";
export const GET_AGENTS_VERBOSE_SUCCESS = "App/GET_AGENTS_VERBOSE_SUCCESS";
export const GET_AGENTS_VERBOSE_ERROR = "App/GET_AGENTS_VERBOSE_ERROR";

export const REFRESH_TOPOLOGY_PENDING = "App/REFRESH_TOPOLOGY_PENDING";
export const REFRESH_TOPOLOGY_SUCCESS = "App/REFRESH_TOPOLOGY_SUCCESS";
export const REFRESH_TOPOLOGY_ERROR = "App/REFRESH_TOPOLOGY_ERROR";

export const MODIFY_ENTITY_PENDING = "App/MODIFY_ENTITY_PENDING";
export const MODIFY_ENTITY_SUCCESS = "App/MODIFY_ENTITY_SUCCESS";
export const MODIFY_ENTITY_ERROR = "App/MODIFY_ENTITY_ERROR";

export const GET_PROJECT_PENDING = "App/GET_PROJECT_PENDING";
export const GET_PROJECT_SUCCESS = "App/GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR = "App/GET_PROJECT_ERROR";

export const UPDATE_PROJECT_PENDING = "App/UPDATE_PROJECT_PENDING";
export const UPDATE_PROJECT_SUCCESS = "App/UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_ERROR = "App/UPDATE_PROJECT_ERROR";

export const GET_PROJECTS_PENDING = "App/GET_PROJECTS_PENDING";
export const GET_PROJECTS_SUCCESS = "App/GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "App/GET_PROJECTS_ERROR";

export const UPDATE_PROJECTS_PENDING = "App/UPDATE_PROJECTS_PENDING";
export const UPDATE_PROJECTS_SUCCESS = "App/UPDATE_PROJECTS_SUCCESS";
export const UPDATE_PROJECTS_ERROR = "App/UPDATE_PROJECTS_ERROR";

export const GET_JOBS_PENDING = "App/GET_JOBS_PENDING";
export const GET_JOBS_SUCCESS = "App/GET_JOBS_SUCCESS";
export const GET_JOBS_ERROR = "App/GET_JOBS_ERROR";

export const ADD_JOB_PENDING = "App/ADD_JOB_PENDING";
export const ADD_JOB_SUCCESS = "App/ADD_JOB_SUCCESS";
export const ADD_JOB_ERROR = "App/ADD_JOB_ERROR";

export const GET_JSON_PENDING = "App/GET_JSON_PENDING";
export const GET_JSON_SUCCESS = "App/GET_JSON_SUCCESS";
export const GET_JSON_ERROR = "App/GET_JSON_ERROR";

export const PUT_JSON_PENDING = "App/PUT_JSON_PENDING";
export const PUT_JSON_SUCCESS = "App/PUT_JSON_SUCCESS";
export const PUT_JSON_ERROR = "App/PUT_JSON_ERROR";

export const GET_LOGS_PENDING = "App/GET_LOGS_PENDING";
export const GET_LOGS_SUCCESS = "App/GET_LOGS_SUCCESS";
export const GET_LOGS_ERROR = "App/GET_LOGS_ERROR";

export const LOGIN_USER_PENDING = "App/LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "App/LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "App/LOGIN_USER_ERROR";
export const LOGOUT_USER = "App/LOGOUT_USER";

export const ADD_SCENARIO_PENDING = "App/ADD_SCENARIO_PENDING";
export const ADD_SCENARIO_SUCCESS = "App/ADD_SCENARIO_SUCCESS";
export const ADD_SCENARIO_ERROR = "App/ADD_SCENARIO_ERROR";

export const REMOVE_SCENARIO_PENDING = "App/REMOVE_SCENARIO_PENDING";
export const REMOVE_SCENARIO_SUCCESS = "App/REMOVE_SCENARIO_SUCCESS";
export const REMOVE_SCENARIO_ERROR = "App/REMOVE_SCENARIO_ERROR";

export const UPDATE_SCENARIO_PENDING = "App/UPDATE_SCENARIO_PENDING";
export const UPDATE_SCENARIO_SUCCESS = "App/UPDATE_SCENARIO_SUCCESS";
export const UPDATE_SCENARIO_ERROR = "App/UPDATE_SCENARIO_ERROR";

export const GET_SCENARIO_INSTANCE_PENDING = "App/GET_SCENARIO_INSTANCE_PENDING";
export const GET_SCENARIO_INSTANCE_SUCCESS = "App/GET_SCENARIO_INSTANCE_SUCCESS";
export const GET_SCENARIO_INSTANCE_ERROR = "App/GET_SCENARIO_INSTANCE_ERROR";

export const PUT_SCENARIO_INSTANCE_PENDING = "App/PUT_SCENARIO_INSTANCE_PENDING";
export const PUT_SCENARIO_INSTANCE_SUCCESS = "App/PUT_SCENARIO_INSTANCE_SUCCESS";
export const PUT_SCENARIO_INSTANCE_ERROR = "App/PUT_SCENARIO_INSTANCE_ERROR";

export const START_SCENARIO_INSTANCE_PENDING = "App/START_SCENARIO_INSTANCE_PENDING";
export const START_SCENARIO_INSTANCE_SUCCESS = "App/START_SCENARIO_INSTANCE_SUCCESS";
export const START_SCENARIO_INSTANCE_ERROR = "App/START_SCENARIO_INSTANCE_ERROR";
export const CLEAR_SCENARIO_INSTANCE_ERROR = "App/CLEAR_SCENARIO_INSTANCE_ERROR";

export const GET_SCENARIO_INSTANCES_PENDING = "App/GET_SCENARIO_INSTANCES_PENDING";
export const GET_SCENARIO_INSTANCES_SUCCESS = "App/GET_SCENARIO_INSTANCES_SUCCESS";
export const GET_SCENARIO_INSTANCES_ERROR = "App/GET_SCENARIO_INSTANCES_ERROR";
export const CLEAR_SCENARIO_INSTANCES = "App/CLEAR_SCENARIO_INSTANCES";

export const DELETE_SCENARIO_INSTANCES_PENDING = "App/DELETE_SCENARIO_INSTANCES_PENDING";
export const DELETE_SCENARIO_INSTANCES_SUCCESS = "App/DELETE_SCENARIO_INSTANCES_SUCCESS";
export const DELETE_SCENARIO_INSTANCES_ERROR = "App/DELETE_SCENARIO_INSTANCES_ERROR";

export const GET_FILTERED_SCENARIO_INSTANCES_PENDING = "App/GET_FILTERED_SCENARIO_INSTANCES_PENDING";
export const GET_FILTERED_SCENARIO_INSTANCES_SUCCESS = "App/GET_FILTERED_SCENARIO_INSTANCES_SUCCESS";
export const GET_FILTERED_SCENARIO_INSTANCES_ERROR = "App/GET_FILTERED_SCENARIO_INSTANCES_ERROR";
export const CLEAR_FILTERED_SCENARIO_INSTANCES = "App/CLEAR_FILTERED_SCENARIO_INSTANCES";

export const GET_LOGIN_CREDENTIALS_PENDING = "App/GET_LOGIN_CREDENTIALS_PENDING";
export const GET_LOGIN_CREDENTIALS_SUCCESS = "App/GET_LOGIN_CREDENTIALS_SUCCESS";
export const GET_LOGIN_CREDENTIALS_ERROR = "App/GET_LOGIN_CREDENTIALS_ERROR";

export const DELETE_LOGIN_CREDENTIALS_PENDING = "App/DELETE_LOGIN_CREDENTIALS_PENDING";
export const DELETE_LOGIN_CREDENTIALS_SUCCESS = "App/DELETE_LOGIN_CREDENTIALS_SUCCESS";
export const DELETE_LOGIN_CREDENTIALS_ERROR = "App/DELETE_LOGIN_CREDENTIALS_ERROR";

export const GET_USERS_LIST_PENDING = "App/GET_USERS_LIST_PENDING";
export const GET_USERS_LIST_SUCCESS = "App/GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_ERROR = "App/GET_USERS_LIST_ERROR";

export const FORM_RESET = "redux-form/RESET";
