#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016-2023 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under
#   the terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.

---

- name: Create Temporary Folder
  tempfile:
    prefix: openbach_installer_
    state: directory
  register: openbach_installer_tempdir

- name: Create temporary SSH key
  shell: ssh-keygen -b 4096 -t rsa -f {{ openbach_installer_tempdir.path }}/openbach_install_rsa -q -N ""
  args:
    creates: "{{ openbach_installer_tempdir.path }}/openbach_install_rsa"
  when: ansible_ssh_private_key_file is not defined

- name: Add Default Collector if Needed
  add_host:
    name: "{{ item }}"
    groups: collector
    openbach_controller: "{{ item }}"
  with_items: "{{ groups.controller | default([]) }}"
  when: ('collector' not in groups) or not groups.collector

- name: Add Default Auditorium if Needed
  add_host:
    name: "{{ item }}"
    groups: auditorium
    openbach_controller: "{{ item }}"
  with_items: "{{ groups.controller | default([]) }}"
  when: ('auditorium' not in groups) or not groups.auditorium

- name: Add Default Agent on Collectors
  add_host:
    name: "{{ item }}"
    groups: agent
    openbach_collector: "{{ item }}"
  with_items: "{{ groups.collector | default([]) }}"

- name: Add Default Agent on Controllers
  add_host:
    name: "{{ item }}"
    groups: agent
    openbach_controller: "{{ item }}"
  with_items: "{{ groups.controller | default([]) }}"
