---

- hosts: all
  tasks:
    - name: Restart Agent Services
      systemd: name={{ item }} state=restarted
      with_items:
        - rstats
        - openbach_agent
      become: yes
      when: openbach_restart is defined and openbach_restart
    - name: Wait for Agent Service to Restart
      wait_for: port={{ openbach_agent_port }} timeout=60
      when: openbach_restart is defined and openbach_restart
    - name: Check Services Status
      service_facts:
      when: collect_metrics is defined and collect_metrics
    - name: Check NTP Status
      shell: ntpq -p
      when: collect_metrics is defined and collect_metrics
