---

- hosts: all
  tasks:
    - name: Change Logs Severity
      template:
        src: rsyslog_job.j2
        dest: /etc/rsyslog.d/60-openbach.conf
        mode: 0644
      vars:
        agent_severity: "{{ severity | default(4) }}"
        agent_local_severity: "{{ local_severity | default(4) }}"
        jobs: "{{ installed_jobs | default([]) }}"
      become: yes

    - name: Restart Service
      systemd:
        name: rsyslog
        state: restarted
        enabled: yes
      become: yes
