# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0001_openbach_2_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='port',
            field=models.SmallIntegerField(default=1112),
        ),
        migrations.AddField(
            model_name='agent',
            name='rstats_port',
            field=models.SmallIntegerField(default=1111),
        ),
    ]
