# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0002_allow_port_customization_on_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='stats_mode',
            field=models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=3),
        ),
    ]
