# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0003_collector_stats_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='openbach_django.Project'),
        ),
    ]
