# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-17 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0004_enforce_project_for_scenarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushfile',
            old_name='address',
            new_name='entity_name',
        ),
    ]
