# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-11 11:34
from __future__ import unicode_literals

from django.db import migrations
import openbach_django.base_models


def populate_default_users_to_empty_list(apps, schema_editor):
    PushFile = apps.get_model('openbach_django', 'PushFile')
    PushFile.objects.all().update(users=[], groups=[])


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0005_adapt_push_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushfile',
            name='users',
            field=openbach_django.base_models.OpenbachFunctionArgument(blank=True, null=True, type=list),
        ),
        migrations.AddField(
            model_name='pushfile',
            name='groups',
            field=openbach_django.base_models.OpenbachFunctionArgument(blank=True, null=True, type=list),
        ),
        migrations.AlterField(
            model_name='pushfile',
            name='local_path',
            field=openbach_django.base_models.OpenbachFunctionArgument(type=list),
        ),
        migrations.AlterField(
            model_name='pushfile',
            name='remote_path',
            field=openbach_django.base_models.OpenbachFunctionArgument(type=list),
        ),

        migrations.RunPython(
            populate_default_users_to_empty_list,
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='pushfile',
            name='users',
            field=openbach_django.base_models.OpenbachFunctionArgument(type=list),
        ),
        migrations.AlterField(
            model_name='pushfile',
            name='groups',
            field=openbach_django.base_models.OpenbachFunctionArgument(type=list),
        ),
    ]
