# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-11-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openbach_django.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0007_lift_500_char_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reboot',
            fields=[
                ('openbachfunction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.OpenbachFunction')),
                ('kernel', openbach_django.base_models.OpenbachFunctionParameter(null=True, type=str)),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.openbachfunction',),
        ),
    ]
