# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-07-09 12:49
from __future__ import unicode_literals

from django.db import migrations
import openbach_django.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0007_lift_500_char_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='setstatisticspolicyjob',
            name='config_file',
            field=openbach_django.base_models.OpenbachFunctionParameter(type=str),
        ),
    ]
