# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-11-17 15:38
from __future__ import unicode_literals

from django.db import migrations
import openbach_django.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0008_reboot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reboot',
            name='entity_name',
            field=openbach_django.base_models.OpenbachFunctionParameter(type=str),
        ),
    ]
