# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-27 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0009_manage_local_statistics_on_agents'),
        ('openbach_django', '0009_reboot_entity_name'),
    ]

    operations = [
    ]
