# Generated by Django 3.0 on 2021-08-04 12:01

from django.db import migrations
import openbach_django.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='setstatisticspolicyjob',
            name='path',
            field=openbach_django.base_models.OpenbachFunctionParameter(type=str),
        ),
    ]
