# Generated by Django 3.2.10 on 2022-02-04 15:19

from django.db import migrations
import openbach_django.base_models


def populate_default_users_to_empty_list(apps, schema_editor):
    PullFile = apps.get_model('openbach_django', 'PullFile')
    for pull in PullFile.objects.all():
        pull.removes = [False] * len(pull.remote_path)
        pull.save()


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0013_pushfile_removes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullfile',
            name='removes',
            field=openbach_django.base_models.OpenbachFunctionParameter(blank=True, null=True, type=list),
        ),

        migrations.RunPython(
            populate_default_users_to_empty_list,
            reverse_code=migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='pullfile',
            name='removes',
            field=openbach_django.base_models.OpenbachFunctionParameter(type=list),
        ),
    ]
