# Generated by Django 3.0 on 2022-11-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0015_failure_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitForRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openbach_function_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_waiters', to='openbach_django.OpenbachFunction')),
                ('openbach_function_waited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbach_django.OpenbachFunction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitForEnded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openbach_function_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ended_waiters', to='openbach_django.OpenbachFunction')),
                ('openbach_function_waited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbach_django.OpenbachFunction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
