# Generated by Django 3.0 on 2022-11-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0017_enumerated_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openbachfunctioninstance',
            name='retry_performed',
        ),
        migrations.AddField(
            model_name='openbachfunctioninstance',
            name='retries_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openbachfunctioninstance',
            name='wait_time',
            field=models.FloatField(default=0.0),
        ),
    ]
