# Generated by Django 3.0 on 2023-09-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0019_status_retry_openbach_function_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='local_severity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='agent',
            name='severity',
            field=models.IntegerField(default=2),
        ),
    ]
