#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016-2020 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under
#   the terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.

---

- set_fact:
    mount: "{{ ansible_mounts | first }}"
                                                                                                                        
- name: setting available resources facts
  set_fact:
     disk_available: "{{ (mount.size_available|int / 1000000000) | round(2, 'common') }}"
     disk_total: "{{ (mount.size_total| int / 1000000000) | round(2, 'common') }}"
     ram: "{{ ansible_facts.devices.vdb.size.split(' ')[0] }}"
     cpu: "{{ ansible_facts.processor_vcpus }}"
     ipv4: "{{ ansible_facts.default_ipv4 }}"
     ipv6: "{{ ansible_facts.default_ipv6 }}"

